package com.nielsmasdorp.sleeply.ui.theme
import androidx.compose.ui.graphics.Color

/**
 * @author Niels Masdorp (NielsMasdorp)
 */

val md_theme_light_primary = Color(0xFF00696e)
val md_theme_light_onPrimary = Color(0xFFffffff)
val md_theme_light_primaryContainer = Color(0xFF6ef6fd)
val md_theme_light_onPrimaryContainer = Color(0xFF002022)
val md_theme_light_secondary = Color(0xFF8d437f)
val md_theme_light_onSecondary = Color(0xFFffffff)
val md_theme_light_secondaryContainer = Color(0xFFffd7f3)
val md_theme_light_onSecondaryContainer = Color(0xFF3a0034)
val md_theme_light_tertiary = Color(0xFF4e5f7c)
val md_theme_light_onTertiary = Color(0xFFffffff)
val md_theme_light_tertiaryContainer = Color(0xFFd4e3ff)
val md_theme_light_onTertiaryContainer = Color(0xFF081c36)
val md_theme_light_error = Color(0xFFba1b1b)
val md_theme_light_errorContainer = Color(0xFFffdad4)
val md_theme_light_onError = Color(0xFFffffff)
val md_theme_light_onErrorContainer = Color(0xFF410001)
val md_theme_light_background = Color(0xFFfafcfc)
val md_theme_light_onBackground = Color(0xFF191c1c)
val md_theme_light_surface = Color(0xFFfafcfc)
val md_theme_light_onSurface = Color(0xFF191c1c)
val md_theme_light_surfaceVariant = Color(0xFFdae4e4)
val md_theme_light_onSurfaceVariant = Color(0xFF3f4949)
val md_theme_light_outline = Color(0xFF6f7979)
val md_theme_light_inverseOnSurface = Color(0xFFeff1f1)
val md_theme_light_inverseSurface = Color(0xFF2e3131)

val md_theme_dark_primary = Color(0xFF4cd9e0)
val md_theme_dark_onPrimary = Color(0xFF00373a)
val md_theme_dark_primaryContainer = Color(0xFF004f53)
val md_theme_dark_onPrimaryContainer = Color(0xFF6ef6fd)
val md_theme_dark_secondary = Color(0xFFffacec)
val md_theme_dark_onSecondary = Color(0xFF56124d)
val md_theme_dark_secondaryContainer = Color(0xFF722b66)
val md_theme_dark_onSecondaryContainer = Color(0xFFffd7f3)
val md_theme_dark_tertiary = Color(0xFFb5c7e9)
val md_theme_dark_onTertiary = Color(0xFF1f314c)
val md_theme_dark_tertiaryContainer = Color(0xFF364763)
val md_theme_dark_onTertiaryContainer = Color(0xFFd4e3ff)
val md_theme_dark_error = Color(0xFFffb4a9)
val md_theme_dark_errorContainer = Color(0xFF930006)
val md_theme_dark_onError = Color(0xFF680003)
val md_theme_dark_onErrorContainer = Color(0xFFffdad4)
val md_theme_dark_background = Color(0xFF191c1c)
val md_theme_dark_onBackground = Color(0xFFe0e3e3)
val md_theme_dark_surface = Color(0xFF191c1c)
val md_theme_dark_onSurface = Color(0xFFe0e3e3)
val md_theme_dark_surfaceVariant = Color(0xFF3f4949)
val md_theme_dark_onSurfaceVariant = Color(0xFFbec8c8)
val md_theme_dark_outline = Color(0xFF899393)
val md_theme_dark_inverseOnSurface = Color(0xFF191c1c)
val md_theme_dark_inverseSurface = Color(0xFFe0e3e3)

val seed = Color(0xFFbaf5f8)
val error = Color(0xFFba1b1b)